---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tester-configmap
  labels:
    app: tester
    component: ue
data:
  config.yml: |
    gnodeb:
      controlif:
        ip: "10.100.50.250"
        port: 9487
      dataif:
        ip: "10.100.50.236"
        port: 2152
      plmnlist:
        mcc: "208"
        mnc: "93"
        tac: "000001"
        gnbid: "000002"
      slicesupportlist:
        sst: "01"
        sd: "010203"
    ue:
      msin: "0000000003"
      key: "70d49a71dd1a2b806a25abe0ef749f1e"
      opc: "6f1bf53d624b3a43af6592854e2444c7"
      amf: "8000"
      sqn: "0000000"
      dnn: "internet"
      hplmn:
        mcc: "208"
        mnc: "93"
      snssai:
        sst: 1
        sd: "010203"
    amfif:
      ip: "10.100.50.249"
      port: 38412
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-tester-ue
  labels:
    app.kubernetes.io/name: tester
    app.kubernetes.io/instance: release-name
    app: tester 
    component: ue
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tester
      app.kubernetes.io/instance: release-name
      app: tester
      component: ue
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tester
        app.kubernetes.io/instance: release-name
        app: tester
        component: ue
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
            { "name": "n2network-release-name-tester",
              "interface": "n2",
              "ips": [ "10.100.50.250/29" ],
              "gateway": [ "10.100.50.254" ]
            },
            { "name": "n3network-release-name-tester",
              "interface": "n3",
              "ips": [ "10.100.50.236/29" ],
              "gateway": [ "10.100.50.238" ]
            }          
            ]'

    spec:
      imagePullSecrets:
        []
      securityContext:
        {}
      containers:
      - image: fhgrings/5g-tester
        name: tester
        ports:
        - name: gnb-ue
          containerPort: 4997
          protocol: UDP
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        command: ["./app"]
        args: ["ue"]
        volumeMounts:
        - mountPath: /workspace/my5G-RANTester/config
          name: tester-volume
        resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 256Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      nodeSelector:
        {}
      affinity:
        {}
      tolerations:
        []

      volumes:
      - name: tester-volume
        configMap:
          name: tester-configmap


---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: n3network-release-name-tester
spec:
  config: '{
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "macvlan",
          "capabilities": { "ips": true },
          "master": "eth0",
          "mode": "bridge",
          "ipam": {
            "type": "static",
            "routes": [
              {
                "dst": "0.0.0.0/0",
                "gw": "10.100.50.238"
              }
            ] 
          }
        }, {
          "capabilities": { "mac": true },
          "type": "tuning"
        }
      ]
    }'

---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: n2network-release-name-tester
spec:
  config: '{
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "macvlan",
          "capabilities": { "ips": true },
          "master": "eth0",
          "mode": "bridge",
          "ipam": {
            "type": "static",
            "routes": [
              {
                "dst": "0.0.0.0/0",
                "gw": "10.100.50.254"
              }
            ] 
          }
        }, {
          "capabilities": { "mac": true },
          "type": "tuning"
        }
      ]
    }'
